select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?

select gender , SUM(purchase_amount)
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?

select MAX(item_purchased) , ROUND(AVG(review_rating::numeric),2) AS "highest review rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type , ROUND(AVG(purchase_amount),2) AS purchase_amount
from customer
where shipping_type in ('Express','Standard') 
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status ,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as average_spend,
SUM(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue , average_spend

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased ,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0) / COUNT(*),2) AS percentage_of_sales
from customer
group by item_purchased
order by percentage_of_sales desc limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.


with customer_type as(
select customer_id , previous_purchases, case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' 
end as customer_segment
from customer
)
select customer_segment , count(*) as "No of customers"
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased products within each category?

with product_purchase as(
select category , 
item_purchased,
count(*) as purchase_count
from customer
group by category , item_purchased
),
ranked_products as (
select category , item_purchased , purchase_count,
ROW_NUMBER() over (
partition by category 
order by purchase_count desc 
) as rn
from product_purchase
)
select category , item_purchased , purchase_count
from ranked_products
where rn <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeated_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group

select age_group , 
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

--Q11. Which customers generate the highest revenue for the business?

WITH customer_revenue AS (
SELECT 
customer_id,
COUNT(*) AS total_orders,
SUM(purchase_amount) AS total_revenue,
ROUND(AVG(purchase_amount),2) AS avg_order_value
FROM customer
GROUP BY customer_id
),
  
customer_segments AS (
SELECT *,
CASE
WHEN total_revenue >= 300 THEN 'High Value Customer'
WHEN total_revenue BETWEEN 150 AND 299 THEN 'Medium Value Customer'
ELSE 'Low Value Customer'
END AS customer_segment
FROM customer_revenue
)

SELECT 
customer_segment,
COUNT(customer_id) AS total_customers,
SUM(total_revenue) AS revenue_generated
FROM customer_segments
GROUP BY customer_segment
ORDER BY revenue_generated DESC;

--Q12. What percentage of customers are repeat buyers?

SELECT CASE 
WHEN previous_purchases > 1 THEN 'Repeat Customer'
ELSE 'New Customer'
END AS customer_type,
COUNT(*) AS total_customers,
ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(),2) AS percentage
FROM customer
GROUP BY customer_type;

